# config/local.yaml

http_server: # конфигурация нашего http-сервера
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 30s
storage:
  username: "user123"
  host: "localhost"
  port: "8080"  
  database: "database" 
  password: "password123"
  maxattempts: 5