# config/local.yaml

httpmicroserver: # конфигурация нашего http-сервера
  host: "localhost"
  orch_port: "8082"
  agent_port: "3030"
  agent_port1: "3031"
  timeout: 5s
  idle_timeout: 30s
storage:
  username: "postgres"
  host: "localhost"
  port: "8080"  
  database: "public" 
  password: "ybazutude423308"
  maxattempts: 5